### ISSUE TITLE
Not able to install on a Pi Zero W

### ISSUE THREAD

**Issue by jkauihou** [TreehouseFalcon/homebridge-kwikset-halo#6]
**Describe Your Problem:**

Have tried several times but have not been able to install. 

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

![image](https://github.com/TreehouseFalcon/homebridge-kwikset-halo/assets/142182168/32fac1c0-9eac-49ce-a65d-5095d74ee668)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:  1.6.1
* **Node.js Version**:  18.17.0
* **NPM Version**: 9.6.7
* **Operating System**: Rasbian

**Comment by TreehouseFalcon** [comment]
This appears to be a physical resource issue. Ensure you have enough available memory on board to run Homebridge.
